version: '3.1'

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - PORT=${PORT}
            - DATABASE_PATH=${DATABASE_PATH}
            - APIKEY_PATH=${APIKEY_PATH}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ~/.flowise:/root/.flowise
        extra_hosts:
            - "host.docker.internal:host-gateway"
